### ISSUE TITLE
[Вопрос] Двухэтапная аунтефикация

### ISSUE THREAD

**Issue by vanja-san** [PurpleHorrorRus/Meridius#1]
Будет ли поддержка в будущем? А то каждый раз включать/выключать не каеф! 🥺

**Comment by PurpleHorrorRus** [comment]
Модуль EasyVK версии 3.0 сейчас находится в разработке. Мы с разработчиком модуля договорились о поддержке двухфакторной аунтефикации в HTTP сессиях. К сожалению, в данный момент нет возможности внедрить ее поддержку, хотя бы просто потому что HTTP сессия не живёт больше суток, а вводить каждый день код из СМС тоже не шибко удобно

**Comment by vanja-san** [comment]
> 
> 
> Модуль EasyVK версии 3.0 сейчас находится в разработке. Мы с разработчиком модуля договорились о поддержке двухфакторной аунтефикации в HTTP сессиях. К сожалению, в данный момент нет возможности внедрить ее поддержку, хотя бы просто потому что HTTP сессия не живёт больше суток, а вводить каждый день код из СМС тоже не шибко удобно

Всё, порос исчерпан! Благодарю за ответ, быстрый и понятный! 😀
