### ISSUE TITLE
Как насчет crossfade'a?

### ISSUE THREAD

**Issue by FiftyFour7250** [PurpleHorrorRus/Meridius#10]
Если вдруг не знаешь, это плавный переход с трека на трек, в Спотифае кстати есть по умолчанию, то есть когда одна дорожка разделена на два трека, то благодаря crossfade'у это звучит как один единый трек. Для примера: Скриптонит, альбом "Дом с нормальными явлениями" - первый и второй трек. Но вообще это штука сейчас очень популярна, почти на каждом модном альбоме. Реализовать по сути не сложно, просто кэшировать следующий трек в очереди. Из мобильных сторонних плееров это есть в [VK U](https://4pda.to/forum/index.php?showtopic=938574) и вроде ещё у кого то видел. В Boom'e разумеется тоже есть, но, полагаю, там не получится подсмотреть, как сделано. В общем, будет круто, если и у тебя появится)

**Comment by vort3** [comment]
Ну тогда уж лучше gapless playback.

**Comment by FiftyFour7250** [comment]
@vort3 Не знаю, возможно в VK U это он и есть, но суть в общем одна. Что бы следующий трек проигрывался без задержек. Совсем.

**Comment by PurpleHorrorRus** [comment]
Реализовано в Meridius 29.0. Лучше поздно, чем никогда.
