### ISSUE TITLE
Исходники?

### ISSUE THREAD

**Issue by DeadNumbers** [PurpleHorrorRus/Meridius#11]
Как насчёт опенсорса?

**Comment by PurpleHorrorRus** [comment]
Ответ на ваш вопрос находится в FAQ в самом приложении и дублируется [здесь](https://vk.com/topic-189978708_41319320)

**Comment by Kostia2004** [comment]
Просто как-то не особо хочется увидеть в логах майнер или что похуже - может хоть сделаешь вторичную открытую версию с урезанным функционалом для паранойков? Можешь опубликовать под лицензией GNU, MIT или Apache

**Comment by PurpleHorrorRus** [comment]
Проект начинался как личный, таковым остаётся до сих пор. Если параноите, то просто не пользуйтесь приложением. У вас есть право мне не доверять, а у меня есть право не загружать исходники, но я оставил все контакты для связи со мной везде, где только можно, чего обычно не делают создатели "майнера или чего похуже"
