### ISSUE TITLE
Недавно пропали Дневной/Недельный плейлисты.

### ISSUE THREAD

**Issue by AquUpd** [PurpleHorrorRus/Meridius#12]
В главном меню раньше были плейлисты под названием Дневной и Недельный. Теперь они пропали.
В браузере они присутствуют
![Снимок экрана от 2021-08-06 14-54-33](https://user-images.githubusercontent.com/47220198/128506771-c3591548-e4a4-472c-85f8-adf355bc4a63.png)
![Снимок экрана от 2021-08-06 14-55-05](https://user-images.githubusercontent.com/47220198/128506798-d9bc125f-c311-46c0-9081-f5a373d6d537.png)

**Comment by PurpleHorrorRus** [comment]
Действительно, ошибка есть. Спасибо, что сообщили, будет исправлено в ближайшее время.

Что о причине этой ошибки - ВК тестирует (судя по всему) новый подход к рекомендациям, делая их в виде обычных плейлистов, избавляясь от коллекций, что были ранее.
![изображение](https://user-images.githubusercontent.com/15189568/128513537-6b398197-a78a-4909-b641-9e87cea4f032.png)
