### ISSUE TITLE
Тень у мини-окна

### ISSUE THREAD

**Issue by AquUpd** [PurpleHorrorRus/Meridius#13]
Windows 10, 21H1 версия.
У мини-окна присутствует тень, которая особо конечно не мешает, но она присутствует.
![image](https://user-images.githubusercontent.com/47220198/129331001-ec33190a-61f9-445a-a768-3d9c73d4df36.png)

**Comment by AquUpd** [comment]
Версия Meridius: 1.9.0
На прошлых версиях такого вроде как не было.
![image](https://user-images.githubusercontent.com/47220198/129331324-86572928-dd84-4e5f-b4fa-8677851638c7.png)

**Comment by PurpleHorrorRus** [comment]
Не совсем понял смысл этих тикетов

**Comment by PurpleHorrorRus** [comment]
Исправлено в 1.9.1. Спасибо за сообщение об ошибке.
