### ISSUE TITLE
Поддержка Arch и других Linux дистрибутивов

### ISSUE THREAD

**Issue by AquUpd** [PurpleHorrorRus/Meridius#15]
В данный момент присутствует только deb пакет, но было бы неплохо если бы был appimage и возможно .pkg.tar.zst.

**Comment by PurpleHorrorRus** [comment]
.AppImage рано или поздно будет. Для Арча появился портирующий [скрипт](https://aur.archlinux.org/packages/meridius-electron-bin). Но создал и отвечаю за этот скрипт не я (Арчем тоже не пользуюсь), поэтому, если что - не ко мне.
