### ISSUE TITLE
Не загружается Главная страница

### ISSUE THREAD

**Issue by AquUpd** [PurpleHorrorRus/Meridius#16]
Не загружается Главная страница после обновления.
![изображение](https://user-images.githubusercontent.com/47220198/129943018-93a410c9-1e2e-4050-bce4-e2304016b90d.png)

**Comment by PurpleHorrorRus** [comment]
Тут только ждать, пока ВК наиграется и перестанет ломать рекомендации.
![изображение](https://user-images.githubusercontent.com/15189568/129950743-e2fe0b52-ec5b-456a-b5fc-a9741d2df964.png)
