### ISSUE TITLE
Не проходит авторизация через vk.

### ISSUE THREAD

**Issue by iqlat** [PurpleHorrorRus/Meridius#24]
Возникла проблема с начальной авторизацией через VK аккаунт: Meridius v 2.1.5 установил с нуля, включая чистку папки **AppData/Roaming/meridiusreborn**, далее ввод данных ВК для входа в meridius -> не авторизуется; пара безуспешных попыток -> капча и опять не пускает.

Помог откат из корзины папки **meridiusreborn** в **appdata**.

Проверено на реальной/виртуальной Win 7 Pro (вряд ли это связано с версией ОС и все же); 

**upd:** специально поставил v2.1.**4** на виртуальную
Win 10 + сброс ip -> авторизация через вк не проходит;

**upd2**: баг локализации > при изменении языка на английский, меню в трее остается на русском языке.

**Comment by PurpleHorrorRus** [comment]
О проблеме известно и фиксу потребуется ещё день для тестирования, пока обойдитесь без деавторизации.
