### ISSUE TITLE
Фриз полосы воспроизведения в мини-плеере

### ISSUE THREAD

**Issue by iqlat** [PurpleHorrorRus/Meridius#25]
**// bug:** при воспроизведении трэка в мини-плеере полоса прогресса воспроизведения и датчик времени воспроизведения "заморожены" => [**gif**](https://i.imgur.com/U67q5h8.gif);

**//** момент с интерфейсом в трее: может быть стоит перенести всплывающее меню при правом клике немного влево, кажется оно слишком прижато к правому углу экрана => [**png**](https://i.imgur.com/2wTIP8x.png); надеюсь, внятно объяснил; как меню выглядело на старых версиях не проверял, просто бросилось в глаза;

спасибо, авторизация через vk заработала.

**Comment by PurpleHorrorRus** [comment]
К сожалению, я не смогу изменить стиль меню трея. Это может сделать только майкрософт.

**Comment by iqlat** [comment]
Ясно, я имел ввиду отступ всплывающего трей-меню Meridius от левой части экрана: видимо, этот отступ задается видимостья или скрытостью других иконок в трее -> [png1](https://i.imgur.com/3r66NHp.png) [png2](https://i.imgur.com/CT95UiC.png)
