### ISSUE TITLE
Вылет приложения Meridius (bug)

### ISSUE THREAD

**Issue by iqlat** [PurpleHorrorRus/Meridius#26]
Обновился до 21.9, с чистым профилем в AppData: вылет при начале воспроизведения любого трэка; на Windows 7 Pro x64, на других версиях ос не проверял; откатился до 21.8; на глаза попался дамп из AppData/Local/CrashDumps => [**link**](https://www.upload.ee/download/13644247/55fb3f1931f81a1caec1/Meridius.exe.7796.dmp)

**Comment by PurpleHorrorRus** [comment]
Исправлено.
