### ISSUE TITLE
Ошибка с миниокном

### ISSUE THREAD

**Issue by AquUpd** [PurpleHorrorRus/Meridius#28]
![изображение](https://user-images.githubusercontent.com/47220198/144712191-6cc415d0-3521-4c9e-99fc-70f3fba02ced.png)

**Происходит при сворачивании приложения. Последняя версия**

![изображение](https://user-images.githubusercontent.com/47220198/144712253-8882d0f4-8e46-4eee-aee0-6fb1e48b3edf.png)

**Comment by PurpleHorrorRus** [comment]
Исправлено.
