### ISSUE TITLE
Не работает стартовая страница VK на версии 2.2.9

### ISSUE THREAD

**Issue by iqlat** [PurpleHorrorRus/Meridius#29]
После обновления Meridius до версии **2.2.9** перестала отображаться стартовая страница => [**1**](https://i.imgur.com/yaZf7Or.png) [**2**](https://i.imgur.com/qkZzZgI.png) ; проверено на Windows 7/10; на версии **2.2.8** все работает как и прежде; думаю, вы уже в курсе; пока что откат на 2.2.8, не критично; спасибо за развитие приложения.

**Comment by PurpleHorrorRus** [comment]
Заскриньте как у вас выглядят ежедневные подборки на сайте

**Comment by iqlat** [comment]
Если вы имеете ввиду старт.страницу - продублирую из предыдущего сообщения => стартовая страница => [**scr1**](https://i.imgur.com/yaZf7Or.png) [**scr2**](https://i.imgur.com/qkZzZgI.png); дополнительно => [**.gif**](https://i.imgur.com/WPl3f3Q.gif); чистый профиль; все остальные категории, кроме "Главная", работают; попробовал откатить блок.адреса из файла hosts, а вдруг -> не помогло; как-то так.

**Comment by PurpleHorrorRus** [comment]
На самом сайте, а не в приложении

**Comment by iqlat** [comment]
вход в аккаунт через firefox 96.0.3:

**Music**: /General /Explore => [**scr1.mp4**](https://imgur.com/a/1aRtvAs)

**Meridius** 2.2.**8**: /Home => [**scr2.mp4**](https://imgur.com/a/II9nr2y)

**Comment by PurpleHorrorRus** [comment]
Обновляйте, проверяйте, дайте знать, помогло ли обновление

**Comment by iqlat** [comment]
авторизация работает, "Домашняя страница" пофиксилась => [**scr**](https://i.imgur.com/Q1b9wWB.png); 
**thx**

**Comment by iqlat** [comment]
**upd:** 1 день после обновления, все стабильно;

**request:** не критично, но если есть возможность => внедрить функцию открытия основного окна приложения при двойном клике на мини-плеере (напр. область обложки альбома) или добавить доп. иконку на сам мини-плеер или через hotkey; часто пользуюсь мини-плеером, при необходимости основного окна приходиться лезть в трей;

скорейшей регенерации) **thx**

**Comment by PurpleHorrorRus** [comment]
Хорошо, спасибо, фича добавлена
