### ISSUE TITLE
Flatpak версия?

### ISSUE THREAD

**Issue by an-yaum** [PurpleHorrorRus/Meridius#31]
Как насчет добавления приложения во [flatpak](https://flatpak.org/) (а конкретно, сразу в магазин приложений [Flathub](https://flathub.org/))?
Можно будет tarball только держать, а от нативного `.deb` пакета и PKGBUILD'а для Арча в AUR отказаться вовсе, потому что контейнеры flatpak совместимы [с добрым количеством дистрибутивов](https://flatpak.org/setup/).

**Comment by PurpleHorrorRus** [comment]
Идея хорошая. Напишите манифест, я его предложу в PR Flathub. И, к слову, за AUR скрипт отвечал не я, поэтому нет возможности обновить или удалить его.

**Comment by PurpleHorrorRus** [comment]
[Опубликовано](https://flathub.org/apps/details/io.github.purplehorrorrus.Meridius)
Спасибо за идею и за помощь.
