### ISSUE TITLE
Раздвоение иконки трея

### ISSUE THREAD

**Issue by an-yaum** [PurpleHorrorRus/Meridius#33]
после переноса линукс версии на flatpak трей работает нормально только до блокировки рабочего стола. После разблокировки появляется вторая иконка трея без значка с системной отрисовкой контекстного меню, как при указывании имени для D-Bus в манифесте.
> Перезапуск приложения решает проблему, но, опять же, только до следующей блокировки.
### Скриншоты:
![Screenshot from 2022-05-19 21-33-45](https://user-images.githubusercontent.com/85643516/169369200-b08703da-7003-4570-95a0-aee65ffbb180.png)
![Screenshot from 2022-05-19 21-36-21](https://user-images.githubusercontent.com/85643516/169369291-7eb6480f-85b4-4a89-9862-71eec13dc355.png)

**DE:** GNOME 42
**OS:** Fedora Workstation 36
**App Version:** 2.4.19

P.S.: *насчет других оболочек не знаю.*

**Comment by PurpleHorrorRus** [comment]
Исправлено.
Переустановите приложение через 4-5 часов, так как версия приложения не будет обновлена, только скрипт установки.
