### ISSUE TITLE
Meridiues 24.20: не запускается

### ISSUE THREAD

**Issue by iqlat** [PurpleHorrorRus/Meridius#34]
**Meridius 24.20**: "бесконечная загрузка" при запуске => [**scr**](https://i.imgur.com/2orkQiA.png); 
так уже было несколько версий назад, вы исправили, написав, что это связано с библиотеками google;

специально протестировал с чистым дефолтным hosts на вирт. win7/10: проблема наблюдается только на win7.

не критично, пока что откатился на предыдущую версию. если есть возможность, исправьте, пожалуйста. 

понимаю, что win10 наиболее актуальна сейчас, в том числе и для девелоперов; буду рад, если ваш проект сможет поддерживать предыдущую версию ос, по возможности)

**Comment by PurpleHorrorRus** [comment]
Исправлено понижением версии Electron.
На будущее, если зашла речь о старых ОС, то, если Electron когда-нибудь объявят о прекращении поддержки Windows 7, то и нам, соответственно, придётся тоже.
