### ISSUE TITLE
Community has hidden audio

### ISSUE THREAD

**Issue by Mojas84** [PurpleHorrorRus/Meridius#39]

**Comment by Mojas84** [comment]
Playlists and site vk only write red Community has hidden audio

**Comment by PurpleHorrorRus** [comment]
New version require to disable Protection from suspicious apps.
Go to VK ID - [Security and login](https://id.vk.com/account/#/security) - Protection from suspicious apps -> disable this
![image](https://user-images.githubusercontent.com/15189568/184557951-a7e0c0f3-82eb-4c1c-b933-084cf11bc65d.png)

**Comment by Mojas84** [comment]
Ok very much thank you. But i can download playlists or more songs not downloading. 0 of 20 example still.....

**Comment by PurpleHorrorRus** [comment]
Will be fix soon

**Comment by Mojas84** [comment]
Ok work!! Super!
