### ISSUE TITLE
Не могу авторизироваться

### ISSUE THREAD

**Issue by zhenyamega** [PurpleHorrorRus/Meridius#40]
При авторизации через приложение нужно ввести код, но ничего не происходит. Не приходит сообщение от администрации, ни смс с кодом.

Спокойно проходил авторизацию через браузер.

Авторизации через TOTP нет.

**Comment by PurpleHorrorRus** [comment]
Попробуйте бета версию 26.0, в которую была добавлена возможность получить код по смс.

**Comment by zhenyamega** [comment]
Всё ещё тихо.

**Comment by PurpleHorrorRus** [comment]
У вас логин по номеру телефона или по почте?

**Comment by zhenyamega** [comment]
По почте. А есть разница?

**Comment by zhenyamega** [comment]
Попробовал всеми тремя на Meridius 26.0 Beta 2

По логину не заходит вообще. По номеру и почте только попытки, но нечего до сих пор не приходит: 

![image](https://user-images.githubusercontent.com/22717765/185884680-a56bd451-f562-447d-8266-8d648c088515.png)

**Comment by PurpleHorrorRus** [comment]
Разница есть. Может из-за того, что у вас авторизация происходит по почте, смс и не приходит, хотя причина для меня всё ещё загадочна. Однако, с HTTP клиентом это может сработать, потому что он имитирует работу браузера. Можно попробовать сменить основной логин по номеру телефона, если в VK есть такая возможность, а можно провенным способом войти через приложение для генерации кодов. Со стороны приложения проблем нет, протестировал у себя, коды приходят как положено.

**Comment by zhenyamega** [comment]
Пришлось поставить TOTP. Теперь смог зарегестрироватся
