### ISSUE TITLE
Не запускается после обновления до 26.1 на Windons 7 [BUG]

### ISSUE THREAD

**Issue by iqlat** [PurpleHorrorRus/Meridius#42]
Обновление Meridius 26.1: не запускается, висит в процессах без какого-либо намека на gui; наблюдается только на Windows 7 x64, на Windows 10 - всё работает; в прошлой раз, если не ошибаюсь, вы это исправили, понизив версию библиотек зависимостей.

**Comment by PurpleHorrorRus** [comment]
Electron уже несколько месяцев и на этот раз не обновлялся, к тому же у меня на виртуальной машине приложение запустилось без проблем, поэтому подтвердить проблему не могу. Попробуйте удалить папку %appdata%/meridiusreborn и начисто переустановить приложение. Если не поможет, запустите приложение из командной строки (из папки с исполняемым файлом) и сообщить об ошибках, если будут.

**Comment by iqlat** [comment]
**my bad**: обновление вашего приложения произвожу через извлечение файлов из вашего установщика и полной заменой их на новые версии; также заменяю ресурсы (иконки) в **meridius.exe** и в папке **build**; а папка **build** > папка **builder**, отсюда и ошибка с запуском; 

можно закрывать issue; 

приложение становится только лучше, thx.
