### ISSUE TITLE
Как авторизоваться?

### ISSUE THREAD

**Issue by L1d0ff** [PurpleHorrorRus/Meridius#43]
![Снимок экрана от 2022-09-04 09-01-19](https://user-images.githubusercontent.com/112759353/188299779-85cbddce-9a87-4bbf-b1e9-f64b2c79fa15.png)
Логин и пароль от чего именно? данные от гитхаба и вк не подходят

**Comment by PurpleHorrorRus** [comment]
От вк, разумеется...
