### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by geb3** [PurpleHorrorRus/Meridius#44]
**Bug description (описание бага)**

При запуске кроме кнопки Открыть инструменты разработчика ничего не появляется и не работает. Удалить и заново установить ситуацию не меняет

**Steps to reproduce (воспроизведение бага)**

На втором скрине в console ошибка

**Expected behaviour (ожидаемое поведение)**

**Screenshots (скриншоты)**

![image](https://user-images.githubusercontent.com/38462483/188303223-db55811b-e80a-4cdd-b0df-c626a7d94999.png)
![image](https://user-images.githubusercontent.com/38462483/188303241-edcddabd-6763-4e4d-9a23-7d7616a2d325.png)

**Device and app information (информация об устройстве и приложении)**
 - OS: [Fedora 36]
 - Meridius version: [e.g. 25.10]

**Additional information (дополнительная информация)**

**Comment by PurpleHorrorRus** [comment]
По какой-то причине не записалась конфигурация об аккаунте в файл, либо её стёрло. Удалите папку конфигурации и попробуйте ещё раз. Проверьте, чтобы у приложения был к чтению и записи в эту папку.
```bash
Flathub: /home/<user>/.var/app/io.github.purplehorrorrus.Meridius/config/meridiusreborn/config
```

**Comment by PurpleHorrorRus** [comment]
Закрыто за неактив.
