### ISSUE TITLE
[BUG] Не грузится дальше заставки

### ISSUE THREAD

**Issue by Ivan-Khar** [PurpleHorrorRus/Meridius#46]
**Bug description (описание бага)**
Meridius не грузится, большое кол-во ошибок `System error: net::ERR_FILE_NOT_FOUND`

**Steps to reproduce (воспроизведение бага)**
- Установить Meridius
- Запустить Meridius

**Expected behaviour (ожидаемое поведение)**
Meridius запускается в главное меню

<details>
<summary><b>Screenshots (скриншоты)</b></summary>
<img src="https://user-images.githubusercontent.com/47220198/194645341-facb8c96-74dd-41fa-a92e-2b8dc72187c6.png" alt="скриншот1">
<img src="https://user-images.githubusercontent.com/47220198/194645352-7fbdc941-1a9e-464b-9b7d-5fe897eb9c56.png" alt="скриншот2">
</details>

**Device and app information (информация об устройстве и приложении)**
 - OS: Windows 10 21H2
 - Meridius version: 26.5

**Additional information (дополнительная информация)**

**Comment by PurpleHorrorRus** [comment]
Жёлтые ошибки ни о чём не говорят, нужна красная.

**Comment by Ivan-Khar** [comment]
Окей, секнду

**Comment by Ivan-Khar** [comment]
![изображение](https://user-images.githubusercontent.com/47220198/194647295-23770e5e-a81e-43dc-ade4-5e926f296a54.png)

**Comment by PurpleHorrorRus** [comment]
Очистите папку кофнфигурациии и переавторизуйтесь в приложение.

> Windows: %appdata%/meridiusreborn/config

> Linux: /home/\<user>/.config/meridiusreborn/config
> > Flathub: /home/\<user>/.var/app/io.github.purplehorrorrus.Meridius/config/meridiusreborn/config

**Comment by Ivan-Khar** [comment]
Ага, спасибо, все заработало
