### ISSUE TITLE
[BUG] Некорректная работа на вертикальных дисплеях

### ISSUE THREAD

**Issue by Khudyakov1** [PurpleHorrorRus/Meridius#47]
**Bug description (описание бага)**
Так как плеер загружает следующие треки только тогда, когда пользователь долистает до конца уже загруженных, а на вертикальном мониторе приложение не загружает достаточно треков, чтобы вообще появилась возможность скроллить, нет возможности пролистать библиотеку треков дальше

**Steps to reproduce (воспроизведение бага)**
Открыть приложение на мониторе, который вмещает больше 20 треков по высоте

**Video (видео)**
https://user-images.githubusercontent.com/74903224/197384598-16de97d7-b0da-4461-85f6-b10bc319eea1.mp4

**Device and app information (информация об устройстве и приложении)**
 - OS: arch 5.19.7
 - Meridius version: v2.7.5-1

**Comment by Khudyakov1** [comment]
И еще на записи по краям окна виден визуальный баг, из-за того, что приложение отрисовывает окно меньшего размера, чем на самом деле занимает. Было бы удобно, если бы в настройках был добавлен пункт, чтобы окно отрисовывалось на всем пространстве, выделенном для него.

**Comment by PurpleHorrorRus** [comment]
Доступно в 27.6.
