### ISSUE TITLE
Как я могу создать учетную запись? Я не понимаю эту часть, не могли бы вы объяснить мне, извините за мое невежество. 

### ISSUE THREAD

**Issue by jd03-m** [PurpleHorrorRus/Meridius#48]
Это должна быть учетная запись MK или я должен ее где-то создать. Спасибо :)
![image](https://user-images.githubusercontent.com/102309952/202833656-bbcb984e-5f92-460c-abd5-7dc66484ec45.png)

**Comment by PurpleHorrorRus** [comment]
Музыкальный плеер для **VK**.
