### ISSUE TITLE
[BUG] Категория "Главная/Home" не отображается

### ISSUE THREAD

**Issue by iqlat** [PurpleHorrorRus/Meridius#50]
Здравствуйте.

1) Баг с категорией "Главная/Home": она уходит в вечную прогрузку ([**scr**](https://i.imgur.com/uzls2ns.png)).

Наблюдается на версиях **2.8.10** и **2.9.0 beta 6**; проверено с чистым профилем, дефолтным файлом hosts; на Windows 7, 10.

Остальные категории отображаются/работают нормально.

В браузере так => [**scr2**](https://i.imgur.com/8JlfIST.png)

2) Скажите, функция двойного клика по заголовку мини-окна для открытия основного окна программы больше работать не будет?

**Comment by PurpleHorrorRus** [comment]
1. Не могу подтвердить эту проблему и у других пользователей всё работает. Приложите ошибки из консоли хотя бы.
2. Это работает, нужно попадать в области между кнопками.

**Comment by iqlat** [comment]
1. на linux - аналогично (v2.8.10);

на linux, win - с дефолтными dns, hosts => проблема остается;

на linux, win из-под vpn => проблема остается;

смена провайдера (с билайн на мегафон) => ноль эффекта;

лог, с чистым профилем => [upload.ee](https://www.upload.ee/download/14817074/13a8ba1d74361c42645f/2023-0-1_11-2-26.txt)

2. с двойным кликом - на виртуальных windows и linux все работает, а вот на основной win7 почему-то перестало; 

исходя из того, что это программный конфликт, отключал все сторонние приложения, скрипты (autohotkey), сбрасывал настройки виз.эфф-в, тем; настройки скорости нажатия двойным кликом, через реестр; 

проблема не решается: двойной клик по области мини-окна на кнопками воспроизведения не дает никакого эффекта; 

понимаю, что это проблема моей конфигурации, просто жаль, что в последних версиях meridius эта фича перестала работать.

**Comment by PurpleHorrorRus** [comment]
Откройте инструменты разработчика (либо в настройках, либо Ctrl + Shift + I), перейдите во вкладку Console и скиньте скриншот красных ошибок.

> просто жаль, что в последних версиях meridius эта фича перестала работать.

Я, возможно, сейчас ещё больше вас расстрою, но после релиза Electron 23 (по прогнозам может к середине-концу февраля) Windows 7, 8, 8.1 перестанут поддерживаться совсем.

**Comment by iqlat** [comment]
1. [scr1](https://i.imgur.com/MC5DW6V.png)      [scr2](https://i.imgur.com/nZ4L7sN.png)

2. не критично; повторюсь на вирт. win7 двойной клик работает; самому интересно, какая настройка, программа не дает работать данной функции (closed); 

а о грядущем обновлении electron'а я помню; скоро во всех кинотеатрах - только win 10 и выше или linux;

**Comment by PurpleHorrorRus** [comment]
Судя по всему, вам VK радиостанции не добавили (во вкладке обзор). Это, конечно, удивительно. Будет исправлено в 29 версии, завтра.
