### ISSUE TITLE
Переместить папку кеша

### ISSUE THREAD

**Issue by AvenCores** [PurpleHorrorRus/Meridius#53]
Данная программа создает создает папку по пути ~/streamer/ на Linux.
Не могли бы вы переместить её в ~/.cache/streamer/

**Comment by PurpleHorrorRus** [comment]
Программа ничего не кэширует, кроме моментов, выполяющихся штатными средствами Electron и Chromium. Если нужно изменить путь хранения файлов стримерского режима, то эта настройка есть уже давно. 

![image](https://github.com/PurpleHorrorRus/Meridius/assets/15189568/6c772e91-b9d3-4ae0-9d2e-5ac17e408f2a)
