### ISSUE TITLE
[BUG] Won't start on Windows 7

### ISSUE THREAD

**Issue by mrx23dot** [PurpleHorrorRus/Meridius#55]
Does it need some VCredist package? Or .NET at given version?
Fails to start for me on Windows 7.
I didn't see any requirement on readme page.

ps. any change to extract the mass download part into commandline? Nothing beats local mp3 in speed :D 
![2023-07-31_212855_zg](https://github.com/PurpleHorrorRus/Meridius/assets/4163396/25ee274a-909c-45bb-918c-5d5dcd644b0f)

**Device and app information (информация об устройстве и приложении)**
 - OS: [e.g. Windows 10, Ubuntu 20.04] 7
 - Meridius version: [e.g. 25.10] 307

**Comment by PurpleHorrorRus** [comment]
Windows < 10 does not supported from February.
