### ISSUE TITLE
[BUG] Download issues

### ISSUE THREAD

**Issue by mrx23dot** [PurpleHorrorRus/Meridius#56]
**Bug description (описание бага)**

After 200+ Downloads the app becomes unusable slow even after ll finished, have to restart the app
uses CPU is at 16%, 1GB RAM and plenty of free.

There is no indication which song has been download, it happily starts it again

P.s. the source code doesn't seem to be complete on github,

**Device and app information (информация об устройстве и приложении)**
 - OS: [e.g. Windows 10, Ubuntu 20.04] Windows 10
 - Meridius version: [e.g. 25.10]  Meridius 30.7

**Comment by PurpleHorrorRus** [comment]
You can adjust two last options if your PC is too weak to convert several audio files at the same time. Download will be slowed, but it reduce impact on PC performance.
![image](https://github.com/PurpleHorrorRus/Meridius/assets/15189568/582c45ee-6592-4fd1-804c-a587f42b24f1)

You can track your download progress on the titlebar.
![image](https://github.com/PurpleHorrorRus/Meridius/assets/15189568/7a740e45-8336-4f89-8529-3eb00b0508f8)

Downloading playlists goes in random order.
