### ISSUE TITLE
[BUG] При появлении скроллбар сдвигает весь контент

### ISSUE THREAD

**Issue by antsif-a** [PurpleHorrorRus/Meridius#57]
**Bug description (описание бага)**
При фокусировке на основном контенте скроллбар появляется и сдвигает часть контента

**Steps to reproduce (воспроизведение бага)**
Зайти в альбом, в котором треки вылезают за размер окна, дальше видно на гифке

**Expected behaviour (ожидаемое поведение)**
Оставить скроллбар и не убирать при разфокусировке

**Screenshots (скриншоты)**

[Запись экрана от 2023-08-18 16-14-51.webm](https://github.com/PurpleHorrorRus/Meridius/assets/55251897/cbdb1158-6b2a-4141-ba9c-ec66146a28f7)

**Device and app information (информация об устройстве и приложении)**
 - OS: ArchLinux, Gnome
 - Meridius version: 3.0.7
 - Electron version: 25.5.0

**Comment by PurpleHorrorRus** [comment]
Версия 3.0.7 поставляется с версией электрона 24.6.3. Проблема этой версии Электрона известна мне, поэтому не тороплюсь с его обновлением. Жалуйтесь в Электрон, а не сюда. Закрыто.
