### ISSUE TITLE
Авторизация через сайт ВК | Authorization via the VK website

### ISSUE THREAD

**Issue by Egorundel** [PurpleHorrorRus/Meridius#58]
RU: Можете сделать авторизацию через сайт ВКонтакте, а не через ваше приложение?

EN: Can you authorize through the VKontakte website, and not through your application?

**Comment by PurpleHorrorRus** [comment]
Нет, это невозможно, нужна работа с куками.

**Comment by nik6olas** [comment]
> Нет, это невозможно, нужна работа с куками.

Если появилась возможность реализовать, то прошу, хотя бы попробуй,
Ибо есть много людей которые хотят пользоваться этой программой, но не могут из-за того, что уже нельзя сменить пароль в вк или посмотреть логин, все через одноразовые коды(((
