### ISSUE TITLE
[Support] Discord RPC? (Linux)

### ISSUE THREAD

**Issue by hinqiwame** [PurpleHorrorRus/Meridius#60]
сегодня поставил программу на свой дистрибутив, раннее видел что в настройках был пункт "интеграция с discord", не нашел. доступна ли эта функция сейчас?

**Comment by PurpleHorrorRus** [comment]
Настройку вернул, однако не факт, что она будет работать (многолетний баг дискорда), вывел предупреждение об этом под ней.

**Comment by hinqiwame** [comment]
> Настройку вернул, однако не факт, что она будет работать (многолетний баг дискорда), вывел предупреждение об этом под ней.

с чем связан баг?
