### ISSUE TITLE
[BUG] Скачивание сломанных треков приводит к зацикливанию

### ISSUE THREAD

**Issue by asoco** [PurpleHorrorRus/Meridius#62]
**Bug description (описание бага)**
При скачивании больших плейлистов часто попадаются треки, не поддающиеся скачиванию (ни через Meridius ни через плагины в браузере). Такие треки выкидывают ошибку "Error: ENOENT: no such file or directory, open"  и программа снова пытается загрузить его, у нее это не выходит и в итоге приводит к бесконечному циклу, в журнале циклично высыпает строку:

[21:49:23] {"errno":-4058,"code":"ENOENT","syscall":"open"}

**Steps to reproduce (воспроизведение бага)**
1. Начать скачивать любой крупный плейлист (примерно от 300 треков)
2. Ждать
3. Профит, к концу процесса набирается n-ое кол-во забаганных треков (примерно каждый сотый трек)

Если нужно, могу прислать примеры конкретных треков, с которыми возникают проблемы

**Expected behaviour (ожидаемое поведение)**
Баганные треки не впадают в цикл и пропускаются.

**Screenshots (скриншоты)**
![photo_2024-04-04_21-48-14](https://github.com/PurpleHorrorRus/Meridius/assets/34142461/e24583b4-602e-4733-97a5-ba5e4d5be861)

**Device and app information (информация об устройстве и приложении)**
 - OS: Windows 11 23H2
 - Meridius: 31.0 / 3.1.0

**Comment by PurpleHorrorRus** [comment]
Исправлено в 3.1.1.
